author:
  name: John Perivolaris
  email: johnperivolaris@icloud.com
  url: 'http://about.me/johnperivolaris'
title: John Perivolaris
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3818474
  brandStrength: 0.1238792745862156
  lightness: 0.4403742
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  rhythmicContrast: 0.2907954
typography_spectrum: 0.06590049155056477
description: 'Perpetually gravitating to islands, cities, and borders'
layout_spectrum: 0.4174173334613442
name: A Map of My Own Making
