typography_spectrum: 0.39372461871244013
color:
  brandStrength: 0.8575241737999022
  lightness: 0.07541883457452059
  saturation: 0.8590357245411724
  rhythmicContrast: 0.2243294375948608
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
layout_spectrum: 0.1462177641224116
author:
  name: John Perivolaris
  email: johnperivolaris@icloud.com
  url: 'http://about.me/johnperivolaris'
name: A Map of My Own Making
title: John Perivolaris
description: 'Perpetually gravitating to islands, cities, and borders'
