typography_spectrum: 0.17792628868483007
color:
  brandStrength: 0.12387927458621562
  lightness: 0.4403741874266416
  saturation: 0.8808855044189841
  rhythmicContrast: 0.2907954554539174
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
layout_spectrum: 0.532701421296224
author:
  name: John Perivolaris
  email: johnperivolaris@icloud.com
  url: 'http://about.me/johnperivolaris'
name: A Map of My Own Making
title: John Perivolaris
description: 'Perpetually gravitating to islands, cities, and borders'
